# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateNewNegativeScores <- function(expression, max_scores, neg_scores) {
    .Call(`_CellAnnotatoR_estimateNewNegativeScores`, expression, max_scores, neg_scores)
}

estimatePariwiseNegativeScoreChange <- function(base_id, neg_scores, pos_scores) {
    .Call(`_CellAnnotatoR_estimatePariwiseNegativeScoreChange`, base_id, neg_scores, pos_scores)
}

estimateDNegativeScores <- function(d_scores, pos_scores, sum_scores, is_positive) {
    .Call(`_CellAnnotatoR_estimateDNegativeScores`, d_scores, pos_scores, sum_scores, is_positive)
}

